#!/bin/bash

if dnsTool -q active_server | grep -q "active"; then
  echo "DNS 1 Server is reachable" >> $(date +"%Y-%m-%d %T")-dns-script.log
  sleep 5
  # Start the failover to DNS 2 Server

  dnsTool -a failover -s dns2
  sleep 2m
  echo "DNS Failover procedure success" >> $(date +"%Y-%m-%d %T")-dns-script.log
#Logs output of the file and appends a date and time stamp
else
  echo "DNS 1 Server is unreachable" >> $(date +"%Y-%m-%d %T")-dns-script.log
  sleep 5
# "DNS 1 Server is unreachable“ Logs and appends a date and timestamp
  # Shutdown the DNS 1 Server

  dnsTool -a shutdown -s dns1
  # Start the failover to DNS 2 Server
  dnsTool -a failover -s dns2
  sleep 2m
  echo "DNS Failover procedure success" >> $(date +"%Y-%m-%d %T")-dns-script.log
fi
